const express = require('express')
const { ApolloServer } = require('apollo-server-express')
const { fork } = require('child_process')
const cors = require('cors')
const port = 5000
const app = express()
const { typeDefs } = require('./SchemaGraphQL/TypeDefs')
const { resolvers } = require('./SchemaGraphQL/Resolvers')
const server = new ApolloServer({ typeDefs, resolvers })
server.applyMiddleware({ app })
const notesRouter = require('./Router/notesRouter')
require('dns').lookup(require('os').hostname(), function (err, add, fam) {
  console.log('addr: ' + add)
})
const authentication = require('./Controller/Auth')
app.use(cors())
app.use(express.json())
app.post('/reg', authentication.registrationUser)
app.post('/login', authentication.loginUser)
app.use('/notes', notesRouter)
const AuthMongo = fork('./WorkerServices/authMongo/worker.js')
const AuthJwt = fork('./WorkerServices/authJwt/worker.js')
const NoteLits = fork('./WorkerServices/notePostgres/worker.js')
app.listen(port, () => console.log(`Example app listening on port port!${port}  Pid - ${process.pid} `))
